/** Mirrors server/src/types/permission.ts. Kept in sync by hand — see server README on the no-shared-package decision. */
export const PERMISSIONS = [
  'user:read',
  'user:write',
  'role:read',
  'machinetype:read',
  'machinetype:write',
  'threadvariety:read',
  'threadvariety:write',
  'threaditem:read',
  'threaditem:write',
  'threadprice:read',
  'buyer:read',
  'buyer:write',
  'season:read',
  'season:write',
  'styletype:read',
  'styletype:write',
  'fabric:read',
  'fabric:write',
  'style:read',
  'style:write',
  'operationlibrary:read',
  'operationlibrary:write',
  'operation:read',
  'operation:write',
  'threadline:write',
  'threadassignment:read',
  'threadassignment:write',
  'chaincheck:read',
  'estimate:read',
  'estimate:write',
  'estimate:submit',
  'estimate:approve',
  'auditlog:read',
  'settings:read',
  'settings:write',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
